Prompt:
#Add task to set kubeconfig for EKS Cluster using aws eks update-kubeconfig command
#Deploy ngnix application to EKS Cluster
#Add code to set kubeconfig for EKS Cluster
#use kubeconfig as ~/.kube/config
#Replica count should be 2
#Expose the application on port 80
#Use LoadBalancer service type

---
- name: Deploy NGINX to EKS Cluster
  hosts: localhost
  gather_facts: no
  vars:
    cluster_name: my-eks-cluster
    region: eu-west-1

  tasks:
    - name: Set kubeconfig for EKS Cluster
      shell: |
        aws eks update-kubeconfig --name {{ cluster_name }} --region {{ region }} --kubeconfig ~/.kube/config
      environment:
        AWS_PROFILE: default

    - name: Create NGINX deployment
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: nginx:latest
                    ports:
                      - containerPort: 80

    - name: Expose NGINX deployment with LoadBalancer
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
          spec:
            type: LoadBalancer
            selector:
              app: nginx
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80